services:
  postgres:
    image: postgres:16
    container_name: library-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: librarydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - library-pgdata:/var/lib/postgresql/data

volumes:
  library-pgdata: